---
title: "Dependencies"
---

In order to use VSCode effectively, there are some additional programs or applications that we also recommend you install or use on your own.

* GitHub:
  * We recommend using GitHub. If you do not already have a GitHub account, we recommend following the [instructions from GitHub](https://docs.github.com/en/get-started).
* Copilot:
  * Our recommended profile installs the GitHub Copilot and Copilot Chat extensions, so they will appear whether or not you intend to use them. To use them you need a GitHub account: there is a free tier, and students and academic staff can get the paid tier at no cost through [GitHub Education](https://github.com/education).
  * [GitHub's setup instructions](https://docs.github.com/en/copilot/quickstart) cover signing in. If you would rather not use Copilot at all, disable the two extensions from the Extensions pane and nothing else in this guide changes.
* Skim:
  * Skim is a PDF viewer, which you can [download from the internet](https://skim-app.sourceforge.io/). We recommend setting this as your default PDF viewer.
  * Once Skim is open, go to the top toolbar menu. Select Skim > Settings.
  * In the settings pane that opens, click Sync on the top right.
  * Check off the boxes for "Check for file changes" and "Reload automatically"
  * In the PDF-TeX Sync support section, set the "Preset" to Visual Studio Code
* MacTeX:
  * MacTeX is the standard TeX distribution on macOS, which you can [download from the internet](https://tug.org/mactex/).
  * If you already have a TeX distribution installed on your computer, you do not need to install MacTeX as well.
* Pandoc:
  * Pandoc allows you to knit `.Rmd` files to PDF files. You can [install the latest release from the internet](https://pandoc.org/installing.html).
